package:
  name: opencv
  version: 2.4.13.2

source:
  url: https://github.com/opencv/opencv/archive/2.4.13.2.zip

build:
  number: 1

requirements:
  build:
   - python 2.7*
   - cmake 3.6.3
   - numpy
   - eigen 3.2.2

  run:
   - python 2.7*
   - numpy
   - libgcc

test:
  imports:
    - cv2
    - cv2.cv

about:
  home: http://opencv.org/
  license: BSD
